spring.application.name=api
spring.datasource.url=jdbc:postgresql://192.168.196.162:5432/eventostec
spring.datasource.username=postgres
spring.datasource.password=@hoanD1323
aws.region = us-east-1
aws.bucket.name = eventostec-imagens


